from typing import TypeVar, overload, Generic, Union, Sequence

from olo.expression import BinaryExpression
from olo.field import Field
from olo.interfaces import SQLASTInterface
from olo.operations import BinaryOperationMixin

T = TypeVar('T')
U = TypeVar('U')
FN = TypeVar('FN', bound='Function')
A = Union[Field[T], T]


class Function(SQLASTInterface[T], BinaryOperationMixin[T], Generic[T]):
    @overload
    def __init__(self, *args: Function[T], **kwargs) -> None: ...

    @overload
    def __init__(self, *args: Field[T], **kwargs) -> None: ...

    @overload
    def __init__(self, *args: T, **kwargs) -> None: ...

    def alias(self: FN, name: str) -> FN: ...


def COUNT(a: A[T]) -> T: ...

def SUM(a: A[T]) -> T: ...

def DISTINCT(a: A[T]) -> T: ...

def AVG(a: A[T]) -> T: ...

def SORT(a: A[T]) -> T: ...

def MAX(a: Union[A[T], Sequence[T]]) -> T: ...

def MIN(a: Union[A[T], Sequence[T]]) -> T: ...

def LENGTH(a: A[str]) -> int: ...

class PartialIf(Function[T], Generic[T]):
    @overload
    def ELSE(self, v: T) -> PartialIf[T]: ...

    @overload
    def ELSE(self, v: U) -> PartialIf[Union[T, U]]: ...

class IF:
    def __init__(self, exp: BinaryExpression) -> None: ...
    def THEN(self, v: T) -> PartialIf[T]: ...
